# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efc98257615b88c224f3efd85055fc8eb651fba9b4ffda50b4f57cb056d187d18eb5b94dfbfb61ab609df217610052287a507e7eecbb6f91b6a1ddf411c7d197

test:
  secret_key_base: 4591c4ccec645e954db66c9c294d129bc3b796a2272cad137a28883f0cf8520125b8893840449618a719ba9bb72783a661a21a540d5dbee8a7e078a3c2847329

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
